import { type NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import PrimaryLinkButtonStyle from "~/components/PrimaryLinkButtonStyle";

const HeroBanner = () => {
  return (
    <section className="mb-24 mt-12 grid grid-cols-1 gap-12 px-4 sm:mt-24 sm:grid-cols-2">
      <div className="flex flex-col gap-4">
        <h1 className="text-6xl">Generate icons with a click of a button</h1>
        <p className="text-1xl">
          Use AI to generate icons in seconds instead of paying designer and
          waiting for them to create them for you
        </p>
        <PrimaryLinkButtonStyle className="self-start" href={"/generate"}>
          Generate Your Icons
        </PrimaryLinkButtonStyle>
      </div>
      <Image
        src={"/banner.jpg"}
        alt="icon-generate-image"
        height={400}
        width={400}
        className="order-first sm:order-none"
      />
    </section>
  );
};

const HomePage: NextPage = () => {
  return (
    <>
      <Head>
        <title>Icon Generator</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="container mx-auto flex  flex-col items-center justify-center">
        <HeroBanner />
      </main>
    </>
  );
};

export default HomePage;
